# Generated by Django 3.2.7 on 2021-09-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.BinaryField(default=b''),
        ),
    ]
