# Generated by Django 3.2.7 on 2021-09-07 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210907_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='members',
            field=models.ManyToManyField(related_name='user_as_member', through='api.Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
