# Generated by Django 3.2.7 on 2021-09-08 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_document_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='document',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.document'),
        ),
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_document', to='api.file'),
        ),
        migrations.AlterField(
            model_name='document',
            name='members',
            field=models.ManyToManyField(through='api.Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
