# Generated by Django 3.2.7 on 2021-09-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210908_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.document'),
        ),
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(max_length=128),
        ),
    ]
