# Generated by Django 3.2.7 on 2021-09-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210908_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ACTUAL'), (2, 'REJECTED'), (3, 'REQUESTED')], default=1),
        ),
    ]
