# Generated by Django 3.2.7 on 2021-09-08 10:36

import api.utils.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='api.document'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ACTUAL'), (2, 'REJECTED'), (3, 'REQUESTED')], default=api.utils.enums.FileType['ACTUAL']),
        ),
    ]
