# Generated by Django 3.2.7 on 2021-09-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210908_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ACTUAL'), (2, 'REJECTED'), (3, 'REQUESTED')], default=1),
        ),
    ]
