# Generated by Django 3.2.7 on 2021-09-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ACTUAL'), (2, 'REJECTED'), (3, 'REQUESTED'), (4, 'VERSION')], default=1),
        ),
    ]
